//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CULTMACEDONIA_v2.Models.CultMacedoniaModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CultMacedoniaDBEntities : DbContext
    {
        public CultMacedoniaDBEntities()
            : base("name=CultMacedoniaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PointImage> PointImage { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Era> Era { get; set; }
        public virtual DbSet<Ethnological> Ethnological { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<ProtectionLevel> ProtectionLevel { get; set; }
        public virtual DbSet<Religion> Religion { get; set; }
        public virtual DbSet<PointOfUser> PointOfUser { get; set; }
        public virtual DbSet<PointVideo> PointVideo { get; set; }
        public virtual DbSet<UserFavorites> UserFavorites { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Point> Point { get; set; }
    }
}
