
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CULTMACEDONIA_v2.Models.CultMacedoniaModel
{

using System;
    using System.Collections.Generic;
    
public partial class PointImage
{

    public int ImageId { get; set; }

    public string ImageFileName { get; set; }

    public string ImageFilePath { get; set; }

    public string ImageTitle { get; set; }

    public int PointId { get; set; }



    public virtual Point Point { get; set; }

}

}
