//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CULTMACEDONIA_v2.App_GlobalResources.Views.Shared.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string AccountManage {
            get {
                return ResourceManager.GetString("AccountManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More!.
        /// </summary>
        public static string AddPoints {
            get {
                return ResourceManager.GetString("AddPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string AppLogin {
            get {
                return ResourceManager.GetString("AppLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string AppLogout {
            get {
                return ResourceManager.GetString("AppLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cult.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string AppRegister {
            get {
                return ResourceManager.GetString("AppRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an online cultural tour in Central Macedonia..
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia.
        /// </summary>
        public static string AppSurname {
            get {
                return ResourceManager.GetString("AppSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field value is not valid.
        /// </summary>
        public static string ContactEmailaNotValid {
            get {
                return ResourceManager.GetString("ContactEmailaNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is required.
        /// </summary>
        public static string ContactEmailRequired {
            get {
                return ResourceManager.GetString("ContactEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Message field is required.
        /// </summary>
        public static string ContactMessageRequired {
            get {
                return ResourceManager.GetString("ContactMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name field is required.
        /// </summary>
        public static string ContactNameRequired {
            get {
                return ResourceManager.GetString("ContactNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/button&gt;There was an error submitting the form, please try again later..
        /// </summary>
        public static string ContactSendFailure {
            get {
                return ResourceManager.GetString("ContactSendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button type=&quot;button&quot; class=&quot;close&quot; data-dismiss=&quot;alert&quot; aria-hidden=&quot;true&quot;&gt;&amp;times;&lt;/button&gt;Your Request for Contact was submitted successfully. We will contact you shortly..
        /// </summary>
        public static string ContactSendSuccess {
            get {
                return ResourceManager.GetString("ContactSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeView {
            get {
                return ResourceManager.GetString("HomeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sights Showcase.
        /// </summary>
        public static string ListAllView {
            get {
                return ResourceManager.GetString("ListAllView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView {
            get {
                return ResourceManager.GetString("LoginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorites.
        /// </summary>
        public static string MyFavorites {
            get {
                return ResourceManager.GetString("MyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Monuments.
        /// </summary>
        public static string MyPoints {
            get {
                return ResourceManager.GetString("MyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Notifications.
        /// </summary>
        public static string NotificationsMessage {
            get {
                return ResourceManager.GetString("NotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your password.
        /// </summary>
        public static string PasswordPlhdr {
            get {
                return ResourceManager.GetString("PasswordPlhdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterView {
            get {
                return ResourceManager.GetString("RegisterView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for sights.
        /// </summary>
        public static string SearchView {
            get {
                return ResourceManager.GetString("SearchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Notifications.
        /// </summary>
        public static string SeeAllNotifications {
            get {
                return ResourceManager.GetString("SeeAllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Edit.
        /// </summary>
        public static string SinglePointEdit {
            get {
                return ResourceManager.GetString("SinglePointEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Registration.
        /// </summary>
        public static string SinglePointNew {
            get {
                return ResourceManager.GetString("SinglePointNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Preview.
        /// </summary>
        public static string SinglePointView {
            get {
                return ResourceManager.GetString("SinglePointView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local CultMacedonia account to log in..
        /// </summary>
        public static string UseLocalAccount {
            get {
                return ResourceManager.GetString("UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your username.
        /// </summary>
        public static string UserNamePlhdr {
            get {
                return ResourceManager.GetString("UserNamePlhdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all Monuments.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for More!.
        /// </summary>
        public static string ViewPoints {
            get {
                return ResourceManager.GetString("ViewPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here :.
        /// </summary>
        public static string YouAreHere {
            get {
                return ResourceManager.GetString("YouAreHere", resourceCulture);
            }
        }
    }
}
