//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class View {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal View() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CULTMACEDONIA_v2.App_GlobalResources.Views.Points.View", typeof(View).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite this!.
        /// </summary>
        public static string AddToFavoritesText {
            get {
                return ResourceManager.GetString("AddToFavoritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        public static string BorderlessText {
            get {
                return ResourceManager.GetString("BorderlessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryCaption {
            get {
                return ResourceManager.GetString("CategoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category selection is required!.
        /// </summary>
        public static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to me....
        /// </summary>
        public static string CloseToMe {
            get {
                return ResourceManager.GetString("CloseToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CommentPanelText {
            get {
                return ResourceManager.GetString("CommentPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we love to hear from you.
        /// </summary>
        public static string ContactSmall {
            get {
                return ResourceManager.GetString("ContactSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Monument Submit Result.
        /// </summary>
        public static string CreateDialogTitle {
            get {
                return ResourceManager.GetString("CreateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument submit failed! Please correct the above errors..
        /// </summary>
        public static string CreateFailure {
            get {
                return ResourceManager.GetString("CreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument Submit failed! Please correct the following..
        /// </summary>
        public static string CreateResultFailure {
            get {
                return ResourceManager.GetString("CreateResultFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Monument {0} successfully submited. Your submission must be  verified by the Administrator. Close the dialog to preview the newly added monument!.
        /// </summary>
        public static string CreateResultSuccess {
            get {
                return ResourceManager.GetString("CreateResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DialogClose {
            get {
                return ResourceManager.GetString("DialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files.
        /// </summary>
        public static string DropFiles {
            get {
                return ResourceManager.GetString("DropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument Edit.
        /// </summary>
        public static string EditActionText {
            get {
                return ResourceManager.GetString("EditActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument Edit Result.
        /// </summary>
        public static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument edit failed! Please correct the above errors..
        /// </summary>
        public static string EditFailure {
            get {
                return ResourceManager.GetString("EditFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument {0} editing was successfull. Close the dialog to view the updated monument!.
        /// </summary>
        public static string EditResultSuccess {
            get {
                return ResourceManager.GetString("EditResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Era.
        /// </summary>
        public static string EraCaption {
            get {
                return ResourceManager.GetString("EraCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Era property selection is required!.
        /// </summary>
        public static string EraRequired {
            get {
                return ResourceManager.GetString("EraRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnological.
        /// </summary>
        public static string EthnologicalCaption {
            get {
                return ResourceManager.GetString("EthnologicalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnological type selection is required!.
        /// </summary>
        public static string EthnologicalRequired {
            get {
                return ResourceManager.GetString("EthnologicalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string FullScreenText {
            get {
                return ResourceManager.GetString("FullScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new sight&apos;s photo registration failed. Error : {0}.
        /// </summary>
        public static string ImageInsertedFailure {
            get {
                return ResourceManager.GetString("ImageInsertedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new sight&apos;s photo registered successfully.
        /// </summary>
        public static string ImageInsertedSuccessfull {
            get {
                return ResourceManager.GetString("ImageInsertedSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Photo Upload failed. Error : {0}.
        /// </summary>
        public static string ImageUploadFailure {
            get {
                return ResourceManager.GetString("ImageUploadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Photo Upload was successful. .
        /// </summary>
        public static string ImageUploadSuccessfull {
            get {
                return ResourceManager.GetString("ImageUploadSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        public static string InfoPanelText {
            get {
                return ResourceManager.GetString("InfoPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You like this!.
        /// </summary>
        public static string isFavorite {
            get {
                return ResourceManager.GetString("isFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Description.
        /// </summary>
        public static string LabelPointDescription {
            get {
                return ResourceManager.GetString("LabelPointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Name.
        /// </summary>
        public static string LabelPointName {
            get {
                return ResourceManager.GetString("LabelPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υear.
        /// </summary>
        public static string labelYear {
            get {
                return ResourceManager.GetString("labelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronological Info.
        /// </summary>
        public static string labelYearDescription {
            get {
                return ResourceManager.GetString("labelYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Image Gallery.
        /// </summary>
        public static string LaunchGalleryText {
            get {
                return ResourceManager.GetString("LaunchGalleryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when you are on the road!.
        /// </summary>
        public static string mobilesmall {
            get {
                return ResourceManager.GetString("mobilesmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monuments.
        /// </summary>
        public static string Monuments {
            get {
                return ResourceManager.GetString("Monuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string NewActionText {
            get {
                return ResourceManager.GetString("NewActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or click.
        /// </summary>
        public static string orclick {
            get {
                return ResourceManager.GetString("orclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size:.
        /// </summary>
        public static string pagesize {
            get {
                return ResourceManager.GetString("pagesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter monument address and try to geocode!.
        /// </summary>
        public static string phdrAddress {
            get {
                return ResourceManager.GetString("phdrAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latitude....
        /// </summary>
        public static string phdrLat {
            get {
                return ResourceManager.GetString("phdrLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitude....
        /// </summary>
        public static string phdrLong {
            get {
                return ResourceManager.GetString("phdrLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter e-mail address.
        /// </summary>
        public static string phdrmail {
            get {
                return ResourceManager.GetString("phdrmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter phone number.
        /// </summary>
        public static string phdrphone {
            get {
                return ResourceManager.GetString("phdrphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter web site.
        /// </summary>
        public static string phdrweb {
            get {
                return ResourceManager.GetString("phdrweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string PhotoGalleryPanelText {
            get {
                return ResourceManager.GetString("PhotoGalleryPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PlaceAddress {
            get {
                return ResourceManager.GetString("PlaceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place and Address.
        /// </summary>
        public static string PlaceAndAddress {
            get {
                return ResourceManager.GetString("PlaceAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string PlaceNomos {
            get {
                return ResourceManager.GetString("PlaceNomos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument&apos;s description is required!.
        /// </summary>
        public static string PointDescrRequired {
            get {
                return ResourceManager.GetString("PointDescrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monument&apos;s name is required!.
        /// </summary>
        public static string PointNameRequired {
            get {
                return ResourceManager.GetString("PointNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Level.
        /// </summary>
        public static string PropectionCaption {
            get {
                return ResourceManager.GetString("PropectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        public static string PropertyCaption {
            get {
                return ResourceManager.GetString("PropertyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type selection is required!.
        /// </summary>
        public static string PropertyRequired {
            get {
                return ResourceManager.GetString("PropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection level selection is required!.
        /// </summary>
        public static string ProtectionRequired {
            get {
                return ResourceManager.GetString("ProtectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter radius here.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string RatingsPanelText {
            get {
                return ResourceManager.GetString("RatingsPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string ReligionCaption {
            get {
                return ResourceManager.GetString("ReligionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religiont selection is required!.
        /// </summary>
        public static string ReligionRequired {
            get {
                return ResourceManager.GetString("ReligionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes!.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Sight!.
        /// </summary>
        public static string SaveMonument {
            get {
                return ResourceManager.GetString("SaveMonument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase of all Monuments.
        /// </summary>
        public static string ShowcaseofallMonuments {
            get {
                return ResourceManager.GetString("ShowcaseofallMonuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Registration Failed! Close this dialog to correct the the errors and please try again..
        /// </summary>
        public static string SightRegistrationErrorInSubmit {
            get {
                return ResourceManager.GetString("SightRegistrationErrorInSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight Registration Failed! Something went wrong! Please be patient and try again..
        /// </summary>
        public static string SightRegistrationSysErrorInSubmit {
            get {
                return ResourceManager.GetString("SightRegistrationSysErrorInSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail us!.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to upload.
        /// </summary>
        public static string ToUpload {
            get {
                return ResourceManager.GetString("ToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Upload Result.
        /// </summary>
        public static string UploadDialogTitle {
            get {
                return ResourceManager.GetString("UploadDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the criteria above to search for monuments!.
        /// </summary>
        public static string UseCriteria {
            get {
                return ResourceManager.GetString("UseCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string VideoGalleryPanelText {
            get {
                return ResourceManager.GetString("VideoGalleryPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View .
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Monument.
        /// </summary>
        public static string ViewMonument {
            get {
                return ResourceManager.GetString("ViewMonument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string WhenAfter {
            get {
                return ResourceManager.GetString("WhenAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string WhenBefore {
            get {
                return ResourceManager.GetString("WhenBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
